
# Define the jobs in the pipeline
jobs:
  main:
    requires: [~commit, ~pr]
    image: node:14
    steps:
      - init: echo "Initializing..."
      - install: npm install
      - test: npm test
      - custom_script: bash ./my_script.sh
      
  second_job:
    requires: [main]
    image: node:14
    steps:
      - echo: echo "Running second job after main"

